name: Exec1 Pipeline

on:
  push:
    branches: [ main ]
    
jobs:
  job1:
    name: Data Ubuntu
    runs-on: ubuntu-latest
    steps:
    - run: date
    
  job2:
    name: Data Windows
    runs-on: windows-latest
    steps:
    - run: date

  job3:
    name: MacOS Windows
    runs-on: windows-latest
    steps:
    - run: date
    
  job4:
    name: Data Windows
    runs-on: windows-latest
    needs: [job1, job2, job3]
    steps:
    - run: echo 'Final'

