name: Exec1 Pipeline

on:
  push:
    branches: [ no-branch ]
    
jobs:
  job1:
    name: Data Ubuntu
    runs-on: ubuntu-latest
    steps:
    - run: date
    
  job2:
    name: Data Windows
    runs-on: windows-latest
    steps:
    - run: date

  job3:
    name: Data MacOS
    runs-on: macos-latest
    steps:
    - run: date
    
  job4:
    name: Final Job
    runs-on: windows-latest
    needs: [job1, job2, job3]
    steps:
    - run: echo 'Final'
    - run: date
